project:
  type: book
  output-dir: docs

book:
  title: "Python Course"
  description: "A hands-on introduction to Python to get you quickly off the ground"
  author: "Fabrizio Damicelli"
  date: "2024-10-14"
  chapters:
    - chapters/index.qmd
    - chapters/01_getting_started.ipynb
    - chapters/010_executing_code.ipynb
    - chapters/02_types_data_structures.ipynb
    - chapters/03_flow_control.ipynb
    - chapters/031_error_handling.ipynb
    - chapters/04_functions.ipynb
    - chapters/041_scope.ipynb
    - chapters/05_comprehensions.ipynb
    - chapters/06_imports.ipynb
    - chapters/061_dependencies.ipynb
    - chapters/062_read_and_write.ipynb
    - chapters/063_common_data_formats.ipynb
    - chapters/08_numpy.ipynb
    - chapters/081_pandas.ipynb
    - chapters/09_plotting.ipynb
    - chapters/10_tests.ipynb
    - chapters/11_cli.ipynb
    - chapters/111_debugging.ipynb
    - chapters/12_oop.ipynb
    - chapters/13_tools.ipynb
    - chapters/lab_explore_data_exercises.ipynb
    - chapters/notebook_workflow.ipynb
    - chapters/999_glossary.ipynb
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
    highlight-style: breeze
    include-after-body: plausible.html
