project:
  type: book
  output-dir: ../docs

book:
  title: "Python Course"
  subtitle: "A friendly, hands-on introduction to Python"
  author: "Fabrizio Damicelli"
  site-url: "https://fabridamicelli.github.io/python-course"
  sharing:
    - "twitter"
    - "linkedin"
    - "facebook"
  navbar:
    right:
      - href: https://github.com/fabridamicelli
        icon: github
      - href: https://x.com/fabridamicelli
        icon: twitter-x
      - href: https://linkedin.com/in/fabridamicelli
        icon: linkedin
  chapters:
    - index.qmd
    - 01_getting_started.ipynb
    - 010_executing_code.ipynb
    - 02_types_data_structures.ipynb
    - 03_flow_control.ipynb
    - 031_error_handling.ipynb
    - 04_functions.ipynb
    - 041_scope.ipynb
    - 05_comprehensions.ipynb
    - 06_imports.ipynb
    - 061_dependencies.ipynb
    - 062_read_and_write.ipynb
    - 063_common_data_formats.ipynb
    - 08_numpy.ipynb
    - 081_pandas.ipynb
    - 09_plotting.ipynb
    - 10_tests.ipynb
    - 11_cli.ipynb
    - 111_debugging.ipynb
    - 12_oop.ipynb
    - 13_tools.ipynb
    - lab_explore_data_exercises.ipynb
    - notebook_workflow.ipynb
    - 999_glossary.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    highlight-style: breeze
    include-in-header: ../plausible.html
